# get name of project
read -p '[🎉] Project name please: ' dirname
printf '\n'
# make dir if not exists
echo '[🎉] Generating dir'
cd
mkdir Projects
cd Projects && mkdir $dirname
cd $dirname
printf '\n'
# generate repo on github
echo "[🎉] Generating git repo..."
cd && python3 GithubBot/gitbot.py $dirname
printf '\n'
cd Projects
cd $dirname
# touch and write readme
echo "[🎉] Writing Readme.md"
touch Readme.md
echo "# Autogenerated Readme"
printf '\n'
# upload project to github
echo "[🎉] Uploading to github"
printf '\n'
git init
git add .
git commit -m "🎉 Initial Commit 🎉"
git remote add origin https://www.github.com/theuitown/$dirname.git
git fetch --prune origin
git reset --hard origin/master
git clean -f -d
git push origin master

printf '\n'

echo '[🎉][🎉] You can now work on your project [🎉][🎉]'
printf '\n'
# Open Project in vscode
code .
