# get name of project
echo "[🎉] Project name please: "
read dirname

# make dir if not exists
echo '[🎉] Generating dir'
cd
mkdir Projects
cd Projects && mkdir $dirname
cd $dirname

# generate repo on github
echo "[🎉] Generating git repo..."
python3 /home/iamharsh/automateGithub/gitbot.py $dirname

# touch and write readme
echo "[🎉] Writing Readme.md"
touch Readme.md
echo "# Autogenerated Readme"

# upload project to github
echo "[🎉] Uploading to github"
git init
git add .
git commit -m "🎉 Initial Commit 🎉"
git remote add origin https://www.github.com/theuitown/$dirname.git
git fetch --prune origin
git reset --hard origin/master
git clean -f -d
git push origin master

echo '[🎉][🎉] You can now work on your project [🎉][🎉]'
# Open Project in vscode
code .
